receivers:
    otlp:
        protocols:
            http:
                endpoint: "0.0.0.0:8080"
exporters:
    logging:

processors:
    batch:

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [logging]
            processors: [batch]
