version: '3.7'

services:
  product-master:
    build: ./product-master
    environment:
      - COLLECTOR_URL=http://monitoring:8080
    ports:
      - 3001:3000
    depends_on:
      - monitoring

  product-information-api:
    build: ./product-information-api
    environment:
      - PRODUCT_MASTER_BASE_URL=http://product-master:3000
      - COLLECTOR_URL=http://monitoring:8080
    ports:
      - 3002:3000
    depends_on:
      - product-master
      - monitoring

  monitoring:
    build: ./monitoring
    command:
      [
        "--config=/local-otel-collector-config.yaml",
        "--log-level=DEBUG"
      ]
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
