version: '3.7'

services:
  product-master:
    build: ./product-master
    ports:
      - 3001:3000

  product-information-api:
    build: ./product-information-api
    environment:
      - PRODUCT_MASTER_BASE_URL=http://product-master:3000
    ports:
      - 3002:3000
    depends_on:
      - product-master
