FROM otel/opentelemetry-collector-contrib:0.46.0

COPY /etc/otel-collector/otel-collector-config-jsonservice-cloudrun.yaml /etc/otel-collector-config.yaml

ARG GCP_PROJECT
ARG SFX_INGEST_TOKEN

ENV GCP_PROJECT=$GCP_PROJECT
ENV SFX_INGEST_TOKEN=$SFX_INGEST_TOKEN

CMD ["--config=/etc/otel-collector-config.yaml"]
