name: Feature
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Image
        run: docker build -t ${{ github.event.repository.name }}:latest .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.event.repository.name }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.unit-tests.outputs.unit-test-result }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Unit Tests
        env:
          NAME: sean
        run: |
          echo "Unit Tests are running..."
          if [ "$NAME" = "sean" ]; then 
            echo "::set-output name=unit-test-result::PASS"
            echo "pass" && exit 0
          else
            echo "::set-output name=unit-test-result::FAIL"
            echo "fail" && exit 1
          fi

  collate-test-results:
    name: Collate Unit Test Results
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Print Results
        run: echo "The result of the Unit Tests was ${{ needs.unit-tests.outputs.result }}"
